backend:
  name: github
  repo: lexeagle/lexeagle
  branch: main
  auth_scope: repo
  publish_mode: editorial_workflow

media_folder: "images/uploads"
collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
