backend:
  name: github
  publish_mode: editorial_workflow 
  repo: lexeagle/lexeagle
  branch: main  
  auth_scope: repo 

media_folder: "images/uploads"
collections:
  - name: "articles" 
    label: "Articles"
    folder: "content/articles" 
    create: true 
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
identity:
  url: "${AUTH0_DOMAIN}" 
  client_id: "${AUTH0_CLIENT_ID}"
  scope: "openid profile email"
